export enum ErrorCodeEnum {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  FORBIDDEN_REQUEST = 'FORBIDDEN_REQUEST',
  ACCESS_UNAUTHORIZED = 'ACCESS_UNAUTHORIZED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT = 'GATEWAY_TIMEOUT',
}

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
