export const Permissions = {
  // Settings & Account & Notifications & Billing
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  EDIT_ACCOUNT: "EDIT_ACCOUNT",
  VIEW_ACCOUNT: "VIEW_ACCOUNT",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  VIEW_SETTINGS: "VIEW_SETTINGS",
  MANAGE_NOTIFICATIONS: "MANAGE_NOTIFICATIONS",
  VIEW_NOTIFICATIONS: "VIEW_NOTIFICATIONS",
  MANAGE_BILLING: "MANAGE_BILLING",
  VIEW_BILLING: "VIEW_BILLING",

  // Support
  CREATE_SUPPORT: "CREATE_SUPPORT",
  EDIT_SUPPORT: "EDIT_SUPPORT",
  VIEW_SUPPORT: "VIEW_SUPPORT",
  DELETE_SUPPORT: "DELETE_SUPPORT",

  // Feedback
  CREATE_FEEDBACK: "CREATE_FEEDBACK",
  EDIT_FEEDBACK: "EDIT_FEEDBACK",
  VIEW_FEEDBACK: "VIEW_FEEDBACK",
  DELETE_FEEDBACK: "DELETE_FEEDBACK",
} as const;

export type PermissionType = keyof typeof Permissions;
export type PermissionValue = typeof Permissions[PermissionType];
