export enum Roles {
  PENDING = 'PENDING',
  STUDENT_USER = 'STUDENT_USER',
  INSTRUCTORS_USER = 'INSTRUCTORS_USER',
  OWNER = 'OWNER',
}

export type RoleType = keyof typeof Roles;

export enum Permissions {
  // Account
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  EDIT_ACCOUNT = 'EDIT_ACCOUNT',
  VIEW_ACCOUNT = 'VIEW_ACCOUNT',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',

  // Settings
  MANAGE_SETTINGS = 'MANAGE_SETTINGS',
  VIEW_SETTINGS = 'VIEW_SETTINGS',

  // Notifications
  MANAGE_NOTIFICATIONS = 'MANAGE_NOTIFICATIONS',
  VIEW_NOTIFICATIONS = 'VIEW_NOTIFICATIONS',

  // Billing
  MANAGE_BILLING = 'MANAGE_BILLING',
  VIEW_BILLING = 'VIEW_BILLING',

  // Students
  VIEW_STUDENTS = 'VIEW_STUDENTS',
  MANAGE_STUDENT_PROGRESS = 'MANAGE_STUDENT_PROGRESS',
  DELETE_STUDENT = 'DELETE_STUDENT',

  // Courses
  ENROLL_COURSE = 'ENROLL_COURSE',
  MANAGE_COURSE = 'MANAGE_COURSE',
  VIEW_COURSE = 'VIEW_COURSE',
  ASSIGN_COURSE = 'ASSIGN_COURSE',
  VIEW_INSTRUCTORS = 'VIEW_INSTRUCTORS',

  // Quizzes
  CREATE_QUIZ = 'CREATE_QUIZ',
  VIEW_QUIZ = 'VIEW_QUIZ',
  EDIT_QUIZ = 'EDIT_QUIZ',
  SUBMIT_QUIZ = 'SUBMIT_QUIZ',
  GRADE_QUIZ = 'GRADE_QUIZ',
  DELETE_QUIZ = 'DELETE_QUIZ',
  VIEW_GRADES = 'VIEW_GRADES',

  // Assignments
  CREATE_ASSIGNMENT = 'CREATE_ASSIGNMENT',
  VIEW_ASSIGNMENT = 'VIEW_ASSIGNMENT',
  EDIT_ASSIGNMENT = 'EDIT_ASSIGNMENT',
  SUBMIT_ASSIGNMENT = 'SUBMIT_ASSIGNMENT',
  GRADE_ASSIGNMENT = 'GRADE_ASSIGNMENT',
  DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT',
  VIEW_ASSIGNMENT_GRADES = 'VIEW_ASSIGNMENT_GRADES',

  // Library
  MANAGE_LIBRARY_ITEM = 'MANAGE_LIBRARY_ITEM',
  VIEW_LIBRARY_ITEM = 'VIEW_LIBRARY_ITEM',
  READ_LIBRARY_ITEM = 'READ_LIBRARY_ITEM',
  WRITE_LIBRARY_REVIEW = 'WRITE_LIBRARY_REVIEW',
  PUBLISH_LIBRARY_ITEM = 'PUBLISH_LIBRARY_ITEM',

  // Problem Solving - Student
  VIEW_STUDENT_PROBLEMS_SOLVING_CONTEST = 'VIEW_STUDENT_PROBLEMS_SOLVING_CONTEST',
  ENROLL_PROBLEMS_SOLVING_CONTEST = 'ENROLL_PROBLEMS_SOLVING_CONTEST',
  VIEW_STUDENT_PROBLEMS_SOLVING_PROBLEM = 'VIEW_STUDENT_PROBLEMS_SOLVING_PROBLEM',
  SUBMIT_STUDENT_PROBLEMS_SOLVING_PROBLEM = 'SUBMIT_STUDENT_PROBLEMS_SOLVING_PROBLEM',

  // Problem Solving - Instructor
  CREATE_PROBLEMS_SOLVING_CONTEST = 'CREATE_PROBLEMS_SOLVING_CONTEST',
  VIEW_INSTRUCTOR_PROBLEMS_SOLVING_CONTEST = 'VIEW_INSTRUCTOR_PROBLEMS_SOLVING_CONTEST',
  EDIT_PROBLEMS_SOLVING_CONTEST = 'EDIT_PROBLEMS_SOLVING_CONTEST',
  DELETE_PROBLEMS_SOLVING_CONTEST = 'DELETE_PROBLEMS_SOLVING_CONTEST',
  ADD_PROBLEMS_SOLVING_PROBLEM = 'ADD_PROBLEMS_SOLVING_PROBLEM',
  VIEW_INSTRUCTOR_PROBLEMS_SOLVING_PROBLEM = 'VIEW_INSTRUCTOR_PROBLEMS_SOLVING_PROBLEM',
  EDIT_PROBLEMS_SOLVING_PROBLEM = 'EDIT_PROBLEMS_SOLVING_PROBLEM',
  DELETE_PROBLEMS_SOLVING_PROBLEM = 'DELETE_PROBLEMS_SOLVING_PROBLEM',

  // AI Tools
  AI_ROADMAP_GENERATOR = 'AI_ROADMAP_GENERATOR',
  GENRATE_ROADMAP = 'GENRATE_ROADMAP',
  VIEW_ROADMAPS = 'VIEW_ROADMAPS',
  DELETE_ROADMAP = 'DELETE_ROADMAP',
  AI_CODE_ASSISTANT = 'AI_CODE_ASSISTANT',
  CREATE_CHAT = 'CREATE_CHAT',
  VIEW_CHATS = 'VIEW_CHATS',
  UPDATE_CHAT = 'UPDATE_CHAT',
  DELETE_CHAT = 'DELETE_CHAT',
  AI_TOPIC_VIDEO_GENERATION = 'AI_TOPIC_VIDEO_GENERATION',
  AI_PRACTICE_PROBLEMS_SOLVING = 'AI_PRACTICE_PROBLEMS_SOLVING',
  AI_PDF_SUMMARY = 'AI_PDF_SUMMARY',

  // Certificates
  GENERATE_CERTIFICATE = 'GENERATE_CERTIFICATE',
  VIEW_CERTIFICATE = 'VIEW_CERTIFICATE',

  // Support
  CREATE_SUPPORT = 'CREATE_SUPPORT',
  VIEW_SUPPORT = 'VIEW_SUPPORT',
  EDIT_SUPPORT = 'EDIT_SUPPORT',
  DELETE_SUPPORT = 'DELETE_SUPPORT',

  // Feedback
  CREATE_FEEDBACK = 'CREATE_FEEDBACK',
  VIEW_FEEDBACK = 'VIEW_FEEDBACK',
  EDIT_FEEDBACK = 'EDIT_FEEDBACK',
  DELETE_FEEDBACK = 'DELETE_FEEDBACK',
}

export type PermissionType = keyof typeof Permissions;
