import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import type { AIFeature } from './ai-usage-ledger.schema';

export type AiIdempotencyDocument = AiIdempotency & Document;

export type IdempotencyStatus = 'PENDING' | 'COMPLETED' | 'FAILED';

/**
 * AiIdempotency — Prevents double-charging on retried requests.
 *
 * Flow:
 *   1. Before AI execution: upsert with status=PENDING (unique key prevents duplicate)
 *   2. On success: update to COMPLETED, store response
 *   3. On failure: update to FAILED (credits already released by AiCreditService)
 *
 * On retry with same idempotency_key:
 *   - If COMPLETED: return cached response, no credit charged
 *   - If FAILED: allow retry (idempotencyKey should be new)
 *   - If PENDING: reject as duplicate in-flight request
 *
 * TTL: documents expire after 24 hours (idempotency window).
 */
@Schema({ collection: 'ai_idempotency', timestamps: true })
export class AiIdempotency {
  /**
   * UUID generated by the API gateway for each unique user action.
   * Must be unique across all users/features.
   */
  @Prop({ type: String, required: true, unique: true, index: true })
  idempotencyKey: string;

  @Prop({ type: Types.ObjectId, ref: 'User', required: true, index: true })
  userId: Types.ObjectId;

  @Prop({
    type: String,
    enum: [
      'ARTICLE_GENERATION',
      'PDF_SUMMARY',
      'ROADMAP_GENERATION',
      'VOICE_CHAT',
      'QUIZ_GENERATION',
      'PROBLEM_SOLVING',
    ],
    required: true,
  })
  feature: AIFeature;

  @Prop({
    type: String,
    enum: ['PENDING', 'COMPLETED', 'FAILED'],
    default: 'PENDING',
    index: true,
  })
  status: IdempotencyStatus;

  /**
   * Cached response for completed requests.
   * Returned directly on duplicate requests to avoid double-charging.
   */
  @Prop({ type: Object })
  cachedResponse?: Record<string, unknown>;

  /**
   * Error details for FAILED requests.
   * The error code determines if credits were released.
   */
  @Prop({ type: String })
  errorCode?: string;

  /**
   * TTL field — MongoDB will automatically delete documents 24h after creation.
   * This limits the idempotency window to 24 hours (reasonable for AI requests).
   */
  @Prop({ type: Date, default: Date.now })
  createdAt: Date;
}

export const AiIdempotencySchema = SchemaFactory.createForClass(AiIdempotency);

/** TTL index: automatically expire idempotency records after 24 hours */
AiIdempotencySchema.index({ createdAt: 1 }, { expireAfterSeconds: 86400 });
