export const Roles = {
  PENDING: "PENDING",
  STUDENT_USER: "STUDENT_USER",
  INSTRUCTORS_USER: "INSTRUCTORS_USER",
} as const;

export type RoleType = keyof typeof Roles;

export const Permissions = {
  // ---------------------------
  // Student Management
  // ---------------------------
  // LMS
  ENROLL_COURSE: "ENROLL_COURSE",
  VIEW_INSTRUCTORS: "VIEW_INSTRUCTORS",
  SUBMIT_QUIZ: "SUBMIT_QUIZ",
  VIEW_GRADES: "VIEW_GRADES",
  SUBMIT_ASSIGNMENT: "SUBMIT_ASSIGNMENT",
  VIEW_ASSIGNMENT_GRADES: "VIEW_ASSIGNMENT_GRADES",
  // Problem Solving
  VIEW_STUDENT_PROBLEMS_SOLVING_CONTEST: "VIEW_STUDENT_PROBLEMS_SOLVING_CONTEST",
  ENROLL_PROBLEMS_SOLVING_CONTEST: "ENROLL_PROBLEMS_SOLVING_CONTEST",
  VIEW_STUDENT_PROBLEMS_SOLVING_PROBLEM: "VIEW_STUDENT_PROBLEMS_SOLVING_PROBLEM",
  SUBMIT_STUDENT_PROBLEMS_SOLVING_PROBLEM: "SUBMIT_STUDENT_PROBLEMS_SOLVING_PROBLEM",
  // AI LMS Tools (Student-focused)
  // Roadmap
  AI_ROADMAP_GENERATOR: "AI_ROADMAP_GENERATOR",
  GENRATE_ROADMAP: "GENRATE_ROADMAP",
  VIEW_ROADMAPS: "VIEW_ROADMAPS",
  DELETE_ROADMAP: "DELETE_ROADMAP",
  // AI Assistant
  AI_CODE_ASSISTANT: "AI_CODE_ASSISTANT",
  CREATE_CHAT: "CREATE_CHAT",
  VIEW_CHATS: "VIEW_CHATS",
  UPDATE_CHAT: "UPDATE_CHAT",
  DELETE_CHAT: "DELETE_CHAT",
  // Topic Video Generator
  AI_TOPIC_VIDEO_GENERATION: "AI_TOPIC_VIDEO_GENERATION",
  // Problem Solving Coach
  AI_PRACTICE_PROBLEMS_SOLVING: "AI_PRACTICE_PROBLEMS_SOLVING",
  // Pdf Summary
  AI_PDF_SUMMARY: "AI_PDF_SUMMARY",

  // ---------------------------
  // Instructor Management
  // ---------------------------
  // Student Management
  VIEW_STUDENTS: "VIEW_STUDENTS",
  MANAGE_STUDENT_PROGRESS: "MANAGE_STUDENT_PROGRESS",
  DELETE_STUDENT: "DELETE_STUDENT",
  // Course Management
  CREATE_COURSE: "CREATE_COURSE",
  VIEW_COURSE: "VIEW_COURSE",
  EDIT_COURSE: "EDIT_COURSE",
  ASSIGN_COURSE: "ASSIGN_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  // Quiz Management
  CREATE_QUIZ: "CREATE_QUIZ",
  VIEW_QUIZ: "VIEW_QUIZ",
  EDIT_QUIZ: "EDIT_QUIZ",
  GRADE_QUIZ: "GRADE_QUIZ",
  DELETE_QUIZ: "DELETE_QUIZ",
  CREATE_ASSIGNMENT: "CREATE_ASSIGNMENT",
  VIEW_ASSIGNMENT: "VIEW_ASSIGNMENT",
  EDIT_ASSIGNMENT: "EDIT_ASSIGNMENT",
  GRADE_ASSIGNMENT: "GRADE_ASSIGNMENT",
  DELETE_ASSIGNMENT: "DELETE_ASSIGNMENT",
  // Problem Solving
  CREATE_PROBLEMS_SOLVING_CONTEST: "CREATE_PROBLEMS_SOLVING_CONTEST",
  VIEW_INSTRUCTOR_PROBLEMS_SOLVING_CONTEST: "VIEW_INSTRUCTOR_PROBLEMS_SOLVING_CONTEST",
  EDIT_PROBLEMS_SOLVING_CONTEST: "EDIT_PROBLEMS_SOLVING_CONTEST",
  DELETE_PROBLEMS_SOLVING_CONTEST: "DELETE_PROBLEMS_SOLVING_CONTEST",
  ADD_PROBLEMS_SOLVING_PROBLEM: "ADD_PROBLEMS_SOLVING_PROBLEM",
  VIEW_INSTRUCTOR_PROBLEMS_SOLVING_PROBLEM: "VIEW_INSTRUCTOR_PROBLEMS_SOLVING_PROBLEM",
  EDIT_PROBLEMS_SOLVING_PROBLEM: "EDIT_PROBLEMS_SOLVING_PROBLEM",
  DELETE_PROBLEMS_SOLVING_PROBLEM: "DELETE_PROBLEMS_SOLVING_PROBLEM",
  // Material Management
  CREATE_MATERIAL: "CREATE_MATERIAL",
  MANAGE_MATERIAL: "MANAGE_MATERIAL",
  VIEW_MATERIAL: "VIEW_MATERIAL",
  READ_LIBRARY_ITEM: "READ_LIBRARY_ITEM",
  WRITE_LIBRARY_REVIEW: "WRITE_LIBRARY_REVIEW",
  EDIT_MATERIAL: "EDIT_MATERIAL",
  PUBLISH_MATERIAL: "PUBLISH_MATERIAL",
  DELETE_MATERIAL: "DELETE_MATERIAL",
  // Certificates
  GENERATE_CERTIFICATE: "GENERATE_CERTIFICATE",
  VIEW_CERTIFICATE: "VIEW_CERTIFICATE",

  // ---------------------------
  // Settings & Account & Notifications & Billing
  // ---------------------------
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  EDIT_ACCOUNT: "EDIT_ACCOUNT",
  VIEW_ACCOUNT: "VIEW_ACCOUNT",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  VIEW_SETTINGS: "VIEW_SETTINGS",
  MANAGE_NOTIFICATIONS: "MANAGE_NOTIFICATIONS",
  VIEW_NOTIFICATIONS: "VIEW_NOTIFICATIONS",
  MANAGE_BILLING: "MANAGE_BILLING",
  VIEW_BILLING: "VIEW_BILLING",

  // ---------------------------
  // Support
  // ---------------------------
  CREATE_SUPPORT: "CREATE_SUPPORT",
  EDIT_SUPPORT: "EDIT_SUPPORT",
  VIEW_SUPPORT: "VIEW_SUPPORT",
  DELETE_SUPPORT: "DELETE_SUPPORT",

  // ---------------------------
  // Feedback
  // ---------------------------
  CREATE_FEEDBACK: "CREATE_FEEDBACK",
  EDIT_FEEDBACK: "EDIT_FEEDBACK",
  VIEW_FEEDBACK: "VIEW_FEEDBACK",
  DELETE_FEEDBACK: "DELETE_FEEDBACK",
} as const;

export type PermissionType = keyof typeof Permissions;
