export const PROBLEM_PATTERNS = {
  CREATE: 'problem.create',
  DELETE: 'problem.delete',
  LIST: 'problem.list',
  GET: 'problem.get',
  SUBMIT: 'submission.create',
  SUBMIT_STATUS: 'submission.status',
  AI_HINT: 'ai.hint',
  AI_HINTS: 'ai.hints',
  AI_SOLUTION: 'ai.solution',
  MARK_SOLVED: 'progress.markSolved',
  GET_SOLVED: 'progress.getSolved',
  GET_PROBLEM_PROGRESS: 'progress.getProblem',
  PATCH_PROBLEM_PROGRESS: 'progress.patchProblem',
  RECORD_SUBMISSION: 'progress.recordSubmission',
  GET_SHEET_PROGRESS: 'progress.getSheet',
  TOUCH_SHEET_PROGRESS: 'progress.touchSheet',
  SHEET_CREATE: 'problemSheet.create',
  SHEET_LIST: 'problemSheet.list',
  SHEET_GET: 'problemSheet.get',
  SHEET_UPDATE: 'problemSheet.update',
  SHEET_PUBLISH: 'problemSheet.publish',
  SHEET_UNPUBLISH: 'problemSheet.unpublish',
  SHEET_DUPLICATE: 'problemSheet.duplicate',
  SHEET_DELETE: 'problemSheet.delete',
  // New sheet problem APIs
  SHEET_PROBLEM_CREATE: 'problemSheet.createProblem',
  SHEET_PROBLEM_UPDATE: 'problemSheet.updateProblem',
  SHEET_PROBLEM_DELETE: 'problemSheet.deleteProblem',
} as const;
