export const ErrorCodeEnum = {
  //! Auth
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",

  AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",

  FORBIDDEN_REQUEST: "FORBIDDEN_REQUEST",

  // Access Control Errors
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",

  // Validation and Resource Errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  //? user
  // User Profile Errors
  USER_PROFILE_NOT_FOUND: "USER_PROFILE_NOT_FOUND",
  USER_PROFILE_UPDATE_FAILED: "USER_PROFILE_UPDATE_FAILED",
  USER_PROFILE_INVALID_DATA: "USER_PROFILE_INVALID_DATA",
  USER_PROFILE_ALREADY_EXISTS: "USER_PROFILE_ALREADY_EXISTS",
  USER_PROFILE_DELETION_FAILED: "USER_PROFILE_DELETION_FAILED",

  // User Settings Errors
  USER_SETTINGS_NOT_FOUND: "USER_SETTINGS_NOT_FOUND",
  USER_SETTINGS_UPDATE_FAILED: "USER_SETTINGS_UPDATE_FAILED",
  USER_SETTINGS_INVALID_CONFIG: "USER_SETTINGS_INVALID_CONFIG",
  USER_SETTINGS_INITIALIZATION_FAILED: "USER_SETTINGS_INITIALIZATION_FAILED",

  // Dashboard Data Errors
  DASHBOARD_DATA_NOT_FOUND: "DASHBOARD_DATA_NOT_FOUND",
  DASHBOARD_DATA_UPDATE_FAILED: "DASHBOARD_DATA_UPDATE_FAILED",
  DASHBOARD_DATA_INVALID_FORMAT: "DASHBOARD_DATA_INVALID_FORMAT",
  DASHBOARD_DATA_SYNC_FAILED: "DASHBOARD_DATA_SYNC_FAILED",

  // Learning Progress Errors
  LEARNING_PROGRESS_NOT_FOUND: "LEARNING_PROGRESS_NOT_FOUND",
  LEARNING_PROGRESS_UPDATE_FAILED: "LEARNING_PROGRESS_UPDATE_FAILED",
  LEARNING_PROGRESS_INVALID_PERCENTAGE: "LEARNING_PROGRESS_INVALID_PERCENTAGE",
  LEARNING_PROGRESS_TRACKING_FAILED: "LEARNING_PROGRESS_TRACKING_FAILED",

  // Course Enrollment Errors
  COURSE_ENROLLMENT_FAILED: "COURSE_ENROLLMENT_FAILED",
  COURSE_ENROLLMENT_NOT_FOUND: "COURSE_ENROLLMENT_NOT_FOUND",
  COURSE_ENROLLMENT_ALREADY_EXISTS: "COURSE_ENROLLMENT_ALREADY_EXISTS",
  COURSE_ENROLLMENT_LIMIT_EXCEEDED: "COURSE_ENROLLMENT_LIMIT_EXCEEDED",

  // Quiz Performance Errors
  QUIZ_PERFORMANCE_NOT_FOUND: "QUIZ_PERFORMANCE_NOT_FOUND",
  QUIZ_PERFORMANCE_UPDATE_FAILED: "QUIZ_PERFORMANCE_UPDATE_FAILED",
  QUIZ_PERFORMANCE_INVALID_SCORE: "QUIZ_PERFORMANCE_INVALID_SCORE",
  QUIZ_PERFORMANCE_TRACKING_FAILED: "QUIZ_PERFORMANCE_TRACKING_FAILED",

  // AI Features Errors
  AI_ROADMAP_GENERATION_FAILED: "AI_ROADMAP_GENERATION_FAILED",
  AI_VIDEO_SUGGESTION_FAILED: "AI_VIDEO_SUGGESTION_FAILED",
  AI_PROBLEM_SOLVING_FAILED: "AI_PROBLEM_SOLVING_FAILED",
  AI_MENTOR_SESSION_FAILED: "AI_MENTOR_SESSION_FAILED",

  // User Activity Errors
  USER_ACTIVITY_TRACKING_FAILED: "USER_ACTIVITY_TRACKING_FAILED",
  USER_ACTIVITY_NOT_FOUND: "USER_ACTIVITY_NOT_FOUND",
  USER_ACTIVITY_INVALID_DATA: "USER_ACTIVITY_INVALID_DATA",

  // Security & Access Control Errors
  USER_ACCESS_UNAUTHORIZED: "USER_ACCESS_UNAUTHORIZED",
  USER_ACCESS_FORBIDDEN: "USER_ACCESS_FORBIDDEN",
  USER_ACCESS_TOKEN_INVALID: "USER_ACCESS_TOKEN_INVALID",
  USER_ACCESS_TOKEN_EXPIRED: "USER_ACCESS_TOKEN_EXPIRED",
  USER_ACCESS_RATE_LIMITED: "USER_ACCESS_RATE_LIMITED",

  // Data Validation Errors
  USER_DATA_VALIDATION_ERROR: "USER_DATA_VALIDATION_ERROR",
  USER_DATA_INVALID_FORMAT: "USER_DATA_INVALID_FORMAT",
  USER_DATA_MISSING_REQUIRED_FIELDS: "USER_DATA_MISSING_REQUIRED_FIELDS",
  USER_DATA_CONSTRAINT_VIOLATION: "USER_DATA_CONSTRAINT_VIOLATION",

  // Resource Management Errors
  USER_RESOURCE_NOT_FOUND: "USER_RESOURCE_NOT_FOUND",
  USER_RESOURCE_ALREADY_EXISTS: "USER_RESOURCE_ALREADY_EXISTS",
  USER_RESOURCE_DELETION_FAILED: "USER_RESOURCE_DELETION_FAILED",
  USER_RESOURCE_UPDATE_FAILED: "USER_RESOURCE_UPDATE_FAILED",

  // Service Integration Errors
  USER_SERVICE_INITIALIZATION_FAILED: "USER_SERVICE_INITIALIZATION_FAILED",
  USER_SERVICE_COMMUNICATION_FAILED: "USER_SERVICE_COMMUNICATION_FAILED",
  USER_SERVICE_DEPENDENCY_FAILED: "USER_SERVICE_DEPENDENCY_FAILED",
  USER_SERVICE_TIMEOUT: "USER_SERVICE_TIMEOUT",

  // Database & Storage Errors
  USER_DATABASE_CONNECTION_FAILED: "USER_DATABASE_CONNECTION_FAILED",
  USER_DATABASE_QUERY_FAILED: "USER_DATABASE_QUERY_FAILED",
  USER_DATABASE_TRANSACTION_FAILED: "USER_DATABASE_TRANSACTION_FAILED",
  USER_CACHE_OPERATION_FAILED: "USER_CACHE_OPERATION_FAILED",

  // System & Infrastructure Errors
  USER_SYSTEM_INTERNAL_ERROR: "USER_SYSTEM_INTERNAL_ERROR",
  USER_SYSTEM_MAINTENANCE: "USER_SYSTEM_MAINTENANCE",
  USER_SYSTEM_OVERLOADED: "USER_SYSTEM_OVERLOADED",
  USER_SYSTEM_UNAVAILABLE: "USER_SYSTEM_UNAVAILABLE",

  // Analytics & Reporting Errors
  USER_ANALYTICS_GENERATION_FAILED: "USER_ANALYTICS_GENERATION_FAILED",
  USER_ANALYTICS_DATA_NOT_FOUND: "USER_ANALYTICS_DATA_NOT_FOUND",
  USER_REPORT_GENERATION_FAILED: "USER_REPORT_GENERATION_FAILED",

  // Notification & Communication Errors
  USER_NOTIFICATION_SEND_FAILED: "USER_NOTIFICATION_SEND_FAILED",
  USER_NOTIFICATION_PREFERENCE_INVALID: "USER_NOTIFICATION_PREFERENCE_INVALID",
  USER_COMMUNICATION_CHANNEL_FAILED: "USER_COMMUNICATION_CHANNEL_FAILED",

  // System Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum;
