export const Roles = {
  ADMIN: "ADMIN",
  INSTRUCTOR: "INSTRUCTOR", // fixed typo
  STUDENT: "STUDENT",
} as const;

export type RoleType = keyof typeof Roles;

export const Permissions = {
  // Instructor Management (Admin)
  ADD_INSTRUCTOR: "ADD_INSTRUCTOR",
  DELETE_INSTRUCTOR: "DELETE_INSTRUCTOR",
  EDIT_INSTRUCTOR: "EDIT_INSTRUCTOR",
  VIEW_INSTRUCTORS: "VIEW_INSTRUCTORS",

  // Student Management (Admin/Instructor)
  ADD_STUDENT: "ADD_STUDENT",
  DELETE_STUDENT: "DELETE_STUDENT",
  EDIT_STUDENT: "EDIT_STUDENT",
  VIEW_STUDENTS: "VIEW_STUDENTS",

  // Course Management
  CREATE_COURSE: "CREATE_COURSE",
  EDIT_COURSE: "EDIT_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  VIEW_COURSE: "VIEW_COURSE",
  ASSIGN_COURSE: "ASSIGN_COURSE", // assign course to instructor/student

  // Quiz Management
  CREATE_QUIZ: "CREATE_QUIZ",
  EDIT_QUIZ: "EDIT_QUIZ",
  DELETE_QUIZ: "DELETE_QUIZ",
  VIEW_QUIZ: "VIEW_QUIZ",
  GRADE_QUIZ: "GRADE_QUIZ",

  // Material Management
  CREATE_MATERIAL: "CREATE_MATERIAL",
  EDIT_MATERIAL: "EDIT_MATERIAL",
  DELETE_MATERIAL: "DELETE_MATERIAL",
  VIEW_MATERIAL: "VIEW_MATERIAL",

  // Discussion / Forums
  CREATE_DISCUSSION: "CREATE_DISCUSSION",
  DELETE_DISCUSSION: "DELETE_DISCUSSION",
  REPLY_DISCUSSION: "REPLY_DISCUSSION",
  MODERATE_DISCUSSION: "MODERATE_DISCUSSION",

  // User Profile & Settings
  EDIT_PROFILE: "EDIT_PROFILE",
  VIEW_PROFILE: "VIEW_PROFILE",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  // Dashboard & Analytics
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  VIEW_ANALYTICS: "VIEW_ANALYTICS",

  // Notifications
  MANAGE_NOTIFICATIONS: "MANAGE_NOTIFICATIONS",
  VIEW_NOTIFICATIONS: "VIEW_NOTIFICATIONS",

  // Certificates
  GENERATE_CERTIFICATE: "GENERATE_CERTIFICATE",
  VIEW_CERTIFICATE: "VIEW_CERTIFICATE",

  // Platform Settings (Admin)
  MANAGE_ROLES: "MANAGE_ROLES",
  VIEW_LOGS: "VIEW_LOGS",
  SYSTEM_SETTINGS: "SYSTEM_SETTINGS",

} as const;

export type PermissionType = keyof typeof Permissions;
