export default () => ({
  //? =========== Backend Configuration ===========
  NATS_URL: process.env.NATS_URL,
  NATS_USER: process.env.NATS_USER,
  NATS_PASSWORD: process.env.NATS_PASSWORD,
  NODE_ENV: process.env.NODE_ENV,

  //* Database configuration (MongoDB),
  MONGO_URI_REMOTE_LMS: process.env.MONGO_URI_REMOTE_LMS,
  MONGO_URI_LOCAL_LMS: process.env.MONGO_URI_LOCAL_LMS,
  MONGO_DB_NAME_LMS: process.env.MONGO_DB_NAME_LMS,

  //? Email configuration (Resend Email Service)
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  EMAIL_FROM: process.env.EMAIL_FROM,

  //? AWS S3 LMS Configuration
  AWS_S3_REGION_LMS: process.env.AWS_S3_REGION_LMS,
  AWS_S3_ACCESS_KEY_ID_LMS: process.env.AWS_S3_ACCESS_KEY_ID_LMS,
  AWS_S3_SECRET_ACCESS_KEY_LMS: process.env.AWS_S3_SECRET_ACCESS_KEY_LMS,
  AWS_S3_BUCKET_LMS: process.env.AWS_S3_BUCKET_LMS,

  //? AWS S3 LMS-AI Configuration
  AWS_ACCESS_KEY_ID_LMS_AI: process.env.AWS_ACCESS_KEY_ID_LMS_AI,
  AWS_SECRET_ACCESS_KEY_LMS_AI: process.env.AWS_SECRET_ACCESS_KEY_LMS_AI,
  AWS_REGION_LMS_AI: process.env.AWS_REGION_LMS_AI,
  AWS_S3_BUCKET_LMS_AI: process.env.AWS_S3_BUCKET_LMS_AI,
  AWS_S3_PRESIGN_EXPIRES_LMS_AI: process.env.AWS_S3_PRESIGN_EXPIRES_LMS_AI,

  //? LMS-AI (dedicated DB or same as LMS — see database.module resolution)
  MONGO_URI_LMS_AI: process.env.MONGO_URI_LMS_AI,
  MONGO_URI_REMOTE_LMS_AI: process.env.MONGO_URI_REMOTE_LMS_AI,
  MONGO_URI_ROADMAP_AI_LMS_AI: process.env.MONGO_URI_ROADMAP_AI_LMS_AI,
  MONGO_URI_PDF_SUMMARY_AI_LMS_AI: process.env.MONGO_URI_PDF_SUMMARY_AI_LMS_AI,
  MONGO_URI_PDF_SUMMARY_AI_AUDIO_LMS_AI: process.env.MONGO_URI_PDF_SUMMARY_AI_AUDIO_LMS_AI,
  MONGO_URI_ASSISTANT_LMS_AI: process.env.MONGO_URI_ASSISTANT_LMS_AI,
  MONGO_URI_PROBLEM_SOLVER_LMS_AI: process.env.MONGO_URI_PROBLEM_SOLVER_LMS_AI,
  MONGO_URI_VIDEO_GEN_LMS_AI: process.env.MONGO_URI_VIDEO_GEN_LMS_AI,
});
