/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unused-vars */
"use server";

import { NextRequest, NextResponse } from "next/server";
import { ChatCohere } from "@langchain/cohere";

// All database and auth logic removed. Only stubs remain.

export const getUserId = async () => {
  // Stub: implement user ID retrieval logic here
  return null;
};

export const getRoadmapsByUserId = async () => {
  // Stub: implement logic to get roadmaps by user ID
  return [];
};

export const getSavedRoadmapsByUserId = async () => {
  // Stub: implement logic to get saved roadmaps by user ID
  return [];
};

export const getRoadmapById = async (id: string) => {
  // Stub: implement logic to get roadmap by ID
  return null;
};

export const saveRoadmap = async (title: string, content: any[]) => {
  // Stub: implement logic to save a roadmap
  return { status: "success", data: null };
};

export const incrementRoadmapSearchCount = async (roadmapId: string) => {
  // Stub: implement logic to increment search count
};

export const changeRoadmapVisibility = async (
  roadmapId: string,
  visibility: any
) => {
  // Stub: implement logic to change roadmap visibility
};

export const isRoadmapGeneratedByUser = async (roadmapId: string) => {
  // Stub: implement logic to check if roadmap is generated by user
  return {
    isGeneratedByUser: false,
    isSavedByUser: false,
    isAuthor: false,
  };
};

export const getPublicRoadmaps = async () => {
  // Stub: implement logic to get public roadmaps
  return [];
};

type PaginatedPublicRoadmap = {
  page: number;
  pageSize: number;
};

export const getPaginatedPublicRoadmaps = async ({
  page,
  pageSize,
}: PaginatedPublicRoadmap) => {
  // Stub: implement logic to get paginated public roadmaps
  return { roadmaps: [], pageCount: 0 };
};

export const checkIfTitleInUsersRoadmaps = async (title: string) => {
  // Stub: implement logic to check if title exists in user's roadmaps
  return { state: false };
};

export const incrementUserCredits = async () => {
  // Stub: implement logic to increment user credits
};

export const deleteRoadmapById = async (
  id: string
): Promise<{ status: string; message?: string }> => {
  // Stub: implement logic to delete roadmap by ID
  return { status: "success", message: "Roadmap successfully deleted." };
};

export const deleteSavedRoadmapById = async (
  id: string
): Promise<{ status: string; message?: string }> => {
  // Stub: implement logic to delete saved roadmap by ID
  return { status: "success", message: "Roadmap successfully deleted." };
};

export const increaseViewsByRoadmapId = async (id: string) => {
  // Stub: implement logic to increase views by roadmap ID
};

export const saveToUserDashboard = async (roadmapId: string) => {
  // Stub: implement logic to save roadmap to user dashboard
  return { status: "success", message: "Roadmap saved successfully." };
};

export const saveNodeDetails = async (
  roadmapId: string,
  nodeName: string,
  content: string,
  books: string,
  youtubeVideoIds: string[]
) => {
  // Stub: implement logic to save node details
  return null;
};

export const findSavedNodeDetails = async (
  roadmapId: string,
  nodeName: string
) => {
  // Stub: implement logic to find saved node details
  return false;
};

export const getTotalRoadmapsGenerated = async () => {
  // Stub: implement logic to get total roadmaps generated
  return 0;
};

export async function POST(req: NextRequest) {
  try {
    const apiKey = req.nextUrl.searchParams.get("apiKey") || process.env.COHERE_API_KEY;
    const body = await req.json();
    const query = body.query;
    if (!query) {
      return NextResponse.json({ status: false, message: "Please send query." }, { status: 400 });
    }
    if (!apiKey) {
      return NextResponse.json({ status: false, message: "Please provide API key." }, { status: 400 });
    }

    const cohere = new ChatCohere({ apiKey, model: "command" });
    // Improved prompt for more reliable JSON output
    const prompt = `Generate a learning roadmap for: ${query}. Respond ONLY in valid JSON with the following structure: {query: string, chapters: {chapterName: [{moduleName: string, moduleDescription: string, link?: string}]}}. Do not include any explanation or markdown, only the JSON.`;
    const response = await cohere.invoke(prompt);
    // Try to extract the JSON from the response
    let text = (response as any)?.content || (response as any)?.text || String(response);
    // Remove any code block markers if present
    text = text.replace(/^```json|^```|```$/g, '').trim();
    let json = null;
    try {
      json = JSON.parse(text);
    } catch (e) {
      return NextResponse.json({ status: false, message: "Error parsing roadmap data.", raw: text, error: String(e) }, { status: 500 });
    }
    return NextResponse.json({ status: true, text: json, roadmapId: "generated-" + Date.now() }, { status: 200 });
  } catch (e) {
    console.log(e);
    return NextResponse.json({ status: false, message: "Something went wrong." }, { status: 400 });
  }
}