import { Role } from '../enums/role.enum';

export type Permission =
  | 'CREATE_ACCOUNT'
  | 'ENROLL_COURSE'
  | 'VIEW_INSTRUCTORS'
  | 'VIEW_QUIZ'
  | 'SUBMIT_QUIZ'
  | 'VIEW_GRADES'
  | 'VIEW_ASSIGNMENT'
  | 'SUBMIT_ASSIGNMENT'
  | 'VIEW_ASSIGNMENT_GRADES'
  | 'VIEW_LIBRARY_ITEM'
  | 'READ_LIBRARY_ITEM'
  | 'WRITE_LIBRARY_REVIEW'
  | 'VIEW_STUDENT_PROBLEMS_SOLVING_CONTEST'
  | 'ENROLL_PROBLEMS_SOLVING_CONTEST'
  | 'VIEW_STUDENT_PROBLEMS_SOLVING_PROBLEM'
  | 'SUBMIT_STUDENT_PROBLEMS_SOLVING_PROBLEM'
  | 'AI_ROADMAP_GENERATOR'
  | 'GENRATE_ROADMAP'
  | 'VIEW_ROADMAPS'
  | 'DELETE_ROADMAP'
  | 'AI_CODE_ASSISTANT'
  | 'CREATE_CHAT'
  | 'VIEW_CHATS'
  | 'UPDATE_CHAT'
  | 'DELETE_CHAT'
  | 'AI_TOPIC_VIDEO_GENERATION'
  | 'AI_PRACTICE_PROBLEMS_SOLVING'
  | 'AI_PDF_SUMMARY'
  | 'EDIT_ACCOUNT'
  | 'VIEW_ACCOUNT'
  | 'CHANGE_PASSWORD'
  | 'MANAGE_SETTINGS'
  | 'VIEW_SETTINGS'
  | 'MANAGE_NOTIFICATIONS'
  | 'VIEW_NOTIFICATIONS'
  | 'MANAGE_BILLING'
  | 'VIEW_BILLING'
  | 'CREATE_SUPPORT'
  | 'VIEW_SUPPORT'
  | 'EDIT_SUPPORT'
  | 'DELETE_SUPPORT'
  | 'CREATE_FEEDBACK'
  | 'VIEW_FEEDBACK'
  | 'EDIT_FEEDBACK'
  | 'DELETE_FEEDBACK'
  | 'VIEW_STUDENTS'
  | 'MANAGE_STUDENT_PROGRESS'
  | 'DELETE_STUDENT'
  | 'MANAGE_COURSE'
  | 'VIEW_COURSE'
  | 'ASSIGN_COURSE'
  | 'CREATE_QUIZ'
  | 'EDIT_QUIZ'
  | 'GRADE_QUIZ'
  | 'DELETE_QUIZ'
  | 'CREATE_ASSIGNMENT'
  | 'EDIT_ASSIGNMENT'
  | 'GRADE_ASSIGNMENT'
  | 'DELETE_ASSIGNMENT'
  | 'CREATE_PROBLEMS_SOLVING_CONTEST'
  | 'VIEW_INSTRUCTOR_PROBLEMS_SOLVING_CONTEST'
  | 'EDIT_PROBLEMS_SOLVING_CONTEST'
  | 'DELETE_PROBLEMS_SOLVING_CONTEST'
  | 'ADD_PROBLEMS_SOLVING_PROBLEM'
  | 'VIEW_INSTRUCTOR_PROBLEMS_SOLVING_PROBLEM'
  | 'EDIT_PROBLEMS_SOLVING_PROBLEM'
  | 'DELETE_PROBLEMS_SOLVING_PROBLEM'
  | 'MANAGE_LIBRARY_ITEM'
  | 'PUBLISH_LIBRARY_ITEM'
  | 'GENERATE_CERTIFICATE'
  | 'VIEW_CERTIFICATE';

export const RolePermissions: Record<Role, Permission[]> = {
  [Role.PENDING]: ['CREATE_ACCOUNT'],

  [Role.STUDENT_USER]: [
    'ENROLL_COURSE',
    'VIEW_INSTRUCTORS',
    'VIEW_QUIZ',
    'SUBMIT_QUIZ',
    'VIEW_GRADES',
    'VIEW_ASSIGNMENT',
    'SUBMIT_ASSIGNMENT',
    'VIEW_ASSIGNMENT_GRADES',
    'VIEW_LIBRARY_ITEM',
    'READ_LIBRARY_ITEM',
    'WRITE_LIBRARY_REVIEW',
    'VIEW_STUDENT_PROBLEMS_SOLVING_CONTEST',
    'ENROLL_PROBLEMS_SOLVING_CONTEST',
    'VIEW_STUDENT_PROBLEMS_SOLVING_PROBLEM',
    'SUBMIT_STUDENT_PROBLEMS_SOLVING_PROBLEM',
    'AI_ROADMAP_GENERATOR',
    'GENRATE_ROADMAP',
    'VIEW_ROADMAPS',
    'DELETE_ROADMAP',
    'AI_CODE_ASSISTANT',
    'CREATE_CHAT',
    'VIEW_CHATS',
    'UPDATE_CHAT',
    'DELETE_CHAT',
    'AI_TOPIC_VIDEO_GENERATION',
    'AI_PRACTICE_PROBLEMS_SOLVING',
    'AI_PDF_SUMMARY',
    'EDIT_ACCOUNT',
    'VIEW_ACCOUNT',
    'CHANGE_PASSWORD',
    'MANAGE_SETTINGS',
    'VIEW_SETTINGS',
    'MANAGE_NOTIFICATIONS',
    'VIEW_NOTIFICATIONS',
    'MANAGE_BILLING',
    'VIEW_BILLING',
    'CREATE_SUPPORT',
    'VIEW_SUPPORT',
    'EDIT_SUPPORT',
    'DELETE_SUPPORT',
    'CREATE_FEEDBACK',
    'VIEW_FEEDBACK',
    'EDIT_FEEDBACK',
    'DELETE_FEEDBACK',
  ],

  [Role.INSTRUCTOR_USER]: [
    'VIEW_STUDENTS',
    'MANAGE_STUDENT_PROGRESS',
    'DELETE_STUDENT',
    'MANAGE_COURSE',
    'VIEW_COURSE',
    'ASSIGN_COURSE',
    'CREATE_QUIZ',
    'VIEW_QUIZ',
    'EDIT_QUIZ',
    'GRADE_QUIZ',
    'DELETE_QUIZ',
    'CREATE_ASSIGNMENT',
    'VIEW_ASSIGNMENT',
    'EDIT_ASSIGNMENT',
    'GRADE_ASSIGNMENT',
    'DELETE_ASSIGNMENT',
    'CREATE_PROBLEMS_SOLVING_CONTEST',
    'VIEW_INSTRUCTOR_PROBLEMS_SOLVING_CONTEST',
    'EDIT_PROBLEMS_SOLVING_CONTEST',
    'DELETE_PROBLEMS_SOLVING_CONTEST',
    'ADD_PROBLEMS_SOLVING_PROBLEM',
    'VIEW_INSTRUCTOR_PROBLEMS_SOLVING_PROBLEM',
    'EDIT_PROBLEMS_SOLVING_PROBLEM',
    'DELETE_PROBLEMS_SOLVING_PROBLEM',
    'MANAGE_LIBRARY_ITEM',
    'VIEW_LIBRARY_ITEM',
    'READ_LIBRARY_ITEM',
    'WRITE_LIBRARY_REVIEW',
    'PUBLISH_LIBRARY_ITEM',
    'GENERATE_CERTIFICATE',
    'VIEW_CERTIFICATE',
    'EDIT_ACCOUNT',
    'VIEW_ACCOUNT',
    'CHANGE_PASSWORD',
    'MANAGE_SETTINGS',
    'VIEW_SETTINGS',
    'MANAGE_NOTIFICATIONS',
    'VIEW_NOTIFICATIONS',
    'MANAGE_BILLING',
    'VIEW_BILLING',
    'CREATE_SUPPORT',
    'VIEW_SUPPORT',
    'EDIT_SUPPORT',
    'DELETE_SUPPORT',
    'CREATE_FEEDBACK',
    'VIEW_FEEDBACK',
    'EDIT_FEEDBACK',
    'DELETE_FEEDBACK',
  ],
};

export const getPermissionsForRole = (role: Role): Permission[] => {
  return RolePermissions[role] ?? [];
};
