export const Permissions = {
  // Quiz Management (must match App service strings exactly)
  CREATE_QUIZ: "CREATE_QUIZ",
  VIEW_QUIZ: "VIEW_QUIZ",
  EDIT_QUIZ: "EDIT_QUIZ",
  GRADE_QUIZ: "GRADE_QUIZ",
  DELETE_QUIZ: "DELETE_QUIZ",
  SUBMIT_QUIZ: "SUBMIT_QUIZ",
  VIEW_GRADES: "VIEW_GRADES",
  // Assignment Management (must match App service strings exactly)
  CREATE_ASSIGNMENT: "CREATE_ASSIGNMENT",
  VIEW_ASSIGNMENT: "VIEW_ASSIGNMENT",
  EDIT_ASSIGNMENT: "EDIT_ASSIGNMENT",
  GRADE_ASSIGNMENT: "GRADE_ASSIGNMENT",
  DELETE_ASSIGNMENT: "DELETE_ASSIGNMENT",
  SUBMIT_ASSIGNMENT: "SUBMIT_ASSIGNMENT",
  VIEW_ASSIGNMENT_GRADES: "VIEW_ASSIGNMENT_GRADES",
  // Material Management
  CREATE_MATERIAL: "CREATE_MATERIAL",
  MANAGE_MATERIAL: "MANAGE_MATERIAL",
  VIEW_MATERIAL: "VIEW_MATERIAL",
  EDIT_MATERIAL: "EDIT_MATERIAL",
  PUBLISH_MATERIAL: "PUBLISH_MATERIAL",
  DELETE_MATERIAL: "DELETE_MATERIAL",
  READ_LIBRARY_ITEM: "READ_LIBRARY_ITEM",
  WRITE_LIBRARY_REVIEW: "WRITE_LIBRARY_REVIEW",
  // Course Management
  CREATE_COURSE: "CREATE_COURSE",
  VIEW_COURSE: "VIEW_COURSE",
  EDIT_COURSE: "EDIT_COURSE",
  ASSIGN_COURSE: "ASSIGN_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  ENROLL_COURSE: "ENROLL_COURSE",
  VIEW_INSTRUCTORS: "VIEW_INSTRUCTORS",
  VIEW_STUDENTS: "VIEW_STUDENTS",
  MANAGE_STUDENT_PROGRESS: "MANAGE_STUDENT_PROGRESS",
  DELETE_STUDENT: "DELETE_STUDENT",
  GENERATE_CERTIFICATE: "GENERATE_CERTIFICATE",
  VIEW_CERTIFICATE: "VIEW_CERTIFICATE",
} as const;

export type PermissionType = keyof typeof Permissions;
export type PermissionValue = typeof Permissions[PermissionType];
